[package]
name = "slotted-egraphs"
version = "0.0.34"
edition = "2021"
description = "E-Graphs with name binding"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/memoryleak47/slotted-egraphs/"

[dependencies]
fnv = "1.0"
