[package]
name = "slotted-egraphs"
version = "0.0.28"
edition = "2021"
description = "E-Graphs with name binding"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/memoryleak47/slotted-egraphs/"

[features]
explanations = []
checks = []
trace = ["tracing/max_level_trace", "tracing/release_max_level_trace", "tracing"]

[package.metadata.docs.rs]
features = ["explanations"]

[dependencies]
slotted-egraphs-derive = { path = "slotted-egraphs-derive" }
fnv = "1.0.7"
tracing = { version = "0.1", features = ["attributes"], optional = true }
symbol_table = { version = "0.3", features = ["global"] }

[dev-dependencies]
rand = "0.8.5"

[profile.release]
debug = true
